def help():
    print('_'*98)
    print('')
    print('Help  -  Let\'s the user know of the availible commands')
    print('GUI  -  Displays a GUI version of the program in a web browser')
    print('Random  -  Displays a random number based on user\'s input.')
    print('Hackermode  -  Displays random bytecode to simulate movie hacking')
    print('Sike8  -  Ask it a random question for a possible outcome')
    print('Logo  -  Displays the program\'s logo')
    print('Clear  -  Clears the terminal screen while program is running')
    print('Exit  -  Exits the program entirely')
    print('_'*98)
